DATA:
  name: "LSFB"
  poses: [["pose","all"],["right_hand","all"],["left_hand","all"], ["face",[61,39,0,269,291,405,17,181,33,159,133,145,46,52,65,55,263,386,362,374,276,282,295,285]]]
  num_keypoints: 99
  num_classes: 610
  min_samples: 20
  oversample: True
  max_len: 32
  target_len: 8
  input_size: [24, 99, 3]
MODEL:
  backbone: "siMLPe"
  use_spatial_fc: False
  feature_norm: "slayernorm"
  depth: 4
  init: "ortho"
LOSS:
  loss_type: "motion"
  relative_motion: True
OPTIMIZATION:
  type_: "Adam"
  batch_size: 128
  lr: 0.00001
  weight_decay: 0.0001
  beta1: 0.9
  beta2: 0.999
  total_steps: 100
  lookahead: False