DATA:
  name: "INCLUDE"
  poses: [["pose",[0,2,5,11,12,13,14,15,16]],["left_hand",[0,4,5,8,9,12,13,16,17,20]],["right_hand",[0,4,5,8,9,12,13,16,17,20]]]
  num_keypoints: 29
  num_classes: 253
  min_samples: 5
  oversample: True
  max_len: 32
  pad_frames: True
  pad_mode: "pad"
  input_size: [32, 29, 3]
  drop_frame: 0.0
  drop_keypoint: 0.0
  block_size: 9
  flip_p: 0.0
  scale: 0.0
  rot: 0
  transform: "none"
  temporal_sampling: "uniform"
  speed: 0.8
  norm: "shoulder"
  shear_std: 0.1
  rot_std: 0.1
MODEL:
  backbone: "ViT"
  hidden_dim: 80
  mlp_dim: 128
  representation_size: 1024
  feature_norm: "layernorm"
  nheads: 4
  depth: 2
  dropout: 0.2
  drop_path: 0.0
  late_dropout: 0.0
  late_drop_path: 0.0
  late_dropout_step: 0
  late_drop_path_step: 0
LOSS:
  loss_type: "CCE"
  label_smoothing: 0.1
OPTIMIZATION:
  type_: "RAdam"
  batch_size: 16
  lr: 0.01
  weight_decay: 0.0001
  beta1: 0.9
  beta2: 0.999
  total_steps: 400
  lrscheduler: "OneCycle"
  max_lr: 0.01
  pct_start: 0.1
