DATA:
  name: "LSFB"
  poses: [["pose","all"],["right_hand","all"],["left_hand","all"], ["face",[61,39,0,269,291,405,17,181,33,159,133,145,46,52,65,55,263,386,362,374,276,282,295,285]]]
  num_keypoints: 99
  num_classes: 637
  min_samples: 20
  oversample: True
  max_len: 64
  input_size: [64, 99, 3]
  random_crop: False
  drop_frame: 0.2
  drop_keypoint: 0.2
  block_size: 5
  scale: 0.05
  rot: 5
MODEL:
  backbone: "conv1d"
  apply_attn: True
  apply_dw_conv: True
  embed_size: 64
  conv_dim: 128
  act_fn: "GELU"
  feature_norm: "batchnorm"
  nheads: 4
  expand_ratio: 2
  depth: 4
  dropout: 0.0
  drop_path: 0.0
  late_dropout: 0.5
  late_drop_path: 0.2
  late_dropout_step: 20
  late_drop_path_step: 20
  init: "ortho"
LOSS:
  loss_type: "CCE"
OPTIMIZATION:
  type_: "RAdam"
  lrscheduler: "None"
  batch_size: 512
  lr: 0.001
  weight_decay: 0.001
  beta1: 0.001
  beta2: 0.999
  total_steps: 100
