DATA:
  name: "LSFB"
  poses: [["pose","all"],["right_hand","all"],["left_hand","all"], ["face",[61,39,0,269,291,405,17,181,33,159,133,145,46,52,65,55,263,386,362,374,276,282,295,285]]]
  num_keypoints: 99
  num_classes: 610
  min_samples: 20
  oversample: True
  max_len: 32
  input_size: [32, 99, 3]
MODEL:
  backbone: "conv1d"
  apply_attn: True
  apply_dw_conv: True
  embed_size: 32
  conv_dim: 64
  act_fn: "GELU"
  feature_norm: "batchnorm"
  nheads: 4
  expand_ratio: 2
  depth: 4
  dropout: 0.0
  drop_path: 0.0
  late_dropout: 0.2
  late_drop_path: 0.1
  late_dropout_step: 10
  late_drop_path_step: 10
  init: "ortho"
LOSS:
  loss_type: "CCE"
OPTIMIZATION:
  type_: "RAdam"
  lrscheduler: "OneCycle"
  batch_size: 1024
  lr: 0.0001
  weight_decay: 0.001
  beta1: 0.9
  beta2: 0.999
  total_steps: 50
