DATA:
  name: "LSFB"
  poses: [["pose",[12,14,16,11,13,15]],["right_hand","all"],["left_hand","all"], ["face",[61,0,291,17,33,159,133,145,263,386,362,374]]]
  num_keypoints: 60
  num_classes: 610
  min_samples: 20
  oversample: True
  max_len: 32
  target_len: 8
  input_size: [24, 60, 3]
MODEL:
  backbone: "CsiMLPe"
  use_spatial_fc: False
  feature_norm: "slayernorm"
  depth: 4
  init: "ortho"
  class_emb_size: 32
LOSS:
  loss_type: "motion"
  relative_motion: True
OPTIMIZATION:
  type_: "Adam"
  batch_size: 1024
  lr: 0.00001
  weight_decay: 0.0001
  beta1: 0.9
  beta2: 0.999
  total_steps: 100
  lookahead: False